 CLASS ztcl_purdocoverallprice  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS ztcl_purdocoverallprice  IMPLEMENTATION.
 ENDCLASS.
